/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

#ifdef CONFIG_PELT_UTIL_HALFLIFE_32
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xfa83b2da,0xf5257d14,0xefe4b99a,
        0xeac0c6e6,0xe5b906e6,0xe0ccdeeb,0xdbfbb796,
        0xd744fcc9,0xd2a81d91,0xce248c14,0xc9b9bd85,
        0xc5672a10,0xc12c4cc9,0xbd08a39e,0xb8fbaf46,
        0xb504f333,0xb123f581,0xad583ee9,0xa9a15ab4,
        0xa5fed6a9,0xa2704302,0x9ef5325f,0x9b8d39b9,
        0x9837f050,0x94f4efa8,0x91c3d373,0x8ea4398a,
        0x8b95c1e3,0x88980e80,0x85aac367,0x82cd8698,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1602, 3170, 4704, 6206, 7675, 9113,10520,11897,13244,14563,
        15853,17116,18352,19561,20744,21902,23035,24144,25229,26291,27330,
        28347,29342,30316,31269,32201,33113,34006,34880,35735,36572,37391,
};

#define LOAD_AVG_PERIOD 32
#define LOAD_AVG_MAX 76396
#define LOAD_AVG_MAX_N 367

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_30
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xfa2727da,0xf4707fd4,0xeedb4007,
        0xe966a51e,0xe411f039,0xdedc66d6,0xd9c552b3,
        0xd4cc01ba,0xcfefc5e5,0xcb2ff529,0xc68be95a,
        0xc203001c,0xbd949ac5,0xb9401e4c,0xb504f333,
        0xb0e28570,0xacd8445b,0xa8e5a29d,0xa50a1614,
        0xa14517cb,0x9d9623df,0x99fcb970,0x96785a91,
        0x93088c35,0x8facd61d,0x8c64c2cc,0x892fdf70,
        0x860dbbda,0x82fdea6a,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1600, 3164, 4692, 6185, 7644, 9069,10462,11823,13153,14453,
        15723,16964,18177,19362,20520,21651,22757,23837,24893,25925,26933,
        27918,28880,29820,30739,31637,32514,33371,34209,35028,
};

#define LOAD_AVG_PERIOD 30
#define LOAD_AVG_MAX 71673
#define LOAD_AVG_MAX_N 344

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_28
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf9bd8e48,0xf3a24b24,0xedad4152,
        0xe7dd818c,0xe2322269,0xdcaa4034,0xd744fcc9,
        0xd2017f74,0xccdef4cc,0xc7dc8e94,0xc2f98399,
        0xbe350f94,0xb98e730b,0xb504f333,0xb097d9d0,
        0xac46751e,0xa81017af,0xa3f41854,0x9ff1d200,
        0x9c08a3b0,0x9837f050,0x947f1ea5,0x90dd9931,
        0x8d52ce1f,0x89de2f2b,0x867f318b,0x83354dd8,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1597, 3155, 4675, 6158, 7605, 9016,10393,11736,13046,14324,
        15571,16788,17975,19133,20263,21365,22440,23489,24512,25510,26484,
        27434,28361,29265,30147,31007,31846,32665,
};

#define LOAD_AVG_PERIOD 28
#define LOAD_AVG_MAX 66950
#define LOAD_AVG_MAX_N 321

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_26
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf943ed16,0xf2b5353d,0xec52a6fd,
        0xe61b18ec,0xe00d6972,0xda287e94,0xd46b45c2,
        0xced4b3a8,0xc963c3f8,0xc417793c,0xbeeedcac,
        0xb9e8fdfc,0xb504f333,0xb041d87e,0xab9ed00c,
        0xa71b01de,0xa2b59ba6,0x9e6dd09d,0x9a42d961,
        0x9633f3cc,0x924062d7,0x8e676e70,0x8aa86360,
        0x87029325,0x837553d5,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1594, 3146, 4658, 6130, 7563, 8958,10317,11640,12928,14182,
        15403,16592,17750,18877,19975,21044,22085,23098,24085,25046,25982,
        26893,27780,28644,29485,30304,
};

#define LOAD_AVG_PERIOD 26
#define LOAD_AVG_MAX 62227
#define LOAD_AVG_MAX_N 298

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_24
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf8b65139,0xf1a1bf37,0xeac0c6e6,
        0xe411f039,0xdd93cdd6,0xd744fcc9,0xd124243d,
        0xcb2ff529,0xc5672a10,0xbfc886ba,0xba52d7ee,
        0xb504f333,0xafddb68e,0xaadc0846,0xa5fed6a9,
        0xa14517cb,0x9cadc957,0x9837f050,0x93e298df,
        0x8facd61d,0x8b95c1e3,0x879c7c96,0x83c02cf9,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1591, 3137, 4639, 6098, 7515, 8892,10230,11530,12793,14020,
        15212,16370,17495,18588,19650,20681,21683,22657,23603,24522,25415,
        26282,27125,27944,
};

#define LOAD_AVG_PERIOD 24
#define LOAD_AVG_MAX 57504
#define LOAD_AVG_MAX_N 275

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_22
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf80f5dd0,0xf05dc6b1,0xe8e94611,
        0xe1aff6e7,0xdab00335,0xd3e7a391,0xcd551eb0,
        0xc6f6c8f7,0xc0cb0410,0xbad03e7c,0xb504f333,
        0xaf67a93b,0xa9f6f34c,0xa4b16f74,0x9f95c6b9,
        0x9aa2acc6,0x95d6df94,0x91312718,0x8cb054f6,
        0x88534433,0x8418d8e8,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1587, 3124, 4614, 6058, 7457, 8812,10125,11398,12631,13826,
        14984,16106,17193,18246,19267,20256,21214,22143,23043,23915,24760,
        25579,
};

#define LOAD_AVG_PERIOD 22
#define LOAD_AVG_MAX 52781
#define LOAD_AVG_MAX_N 252

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_20
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf7479a6d,0xeedb4007,0xe6b859ad,
        0xdedc66d6,0xd744fcc9,0xcfefc5e5,0xc8da80e0,
        0xc203001c,0xbb6728fa,0xb504f333,0xaeda6839,
        0xa8e5a29d,0xa324cd78,0x9d9623df,0x9837f050,
        0x93088c35,0x8e065f59,0x892fdf70,0x84838f9e,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1582, 3110, 4586, 6011, 7388, 8718,10003,11244,12443,13601,
        14719,15799,16843,17851,18825,19765,20673,21551,22399,23218,
};

#define LOAD_AVG_PERIOD 20
#define LOAD_AVG_MAX 48058
#define LOAD_AVG_MAX_N 229

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_18
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf6544d25,0xed062008,0xe411f039,
        0xdb745776,0xd32a105b,0xcb2ff529,0xc382fe8e,
        0xbc204284,0xb504f333,0xae2e5de1,0xa799e9eb,
        0xa14517cb,0x9b2d8023,0x9550d2d4,0x8facd61d,
        0x8a3f65c3,0x85067241,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1576, 3092, 4551, 5955, 7306, 8606, 9857,11060,12218,13332,
        14404,15435,16428,17383,18302,19186,20037,20856,
};

#define LOAD_AVG_PERIOD 18
#define LOAD_AVG_MAX 43335
#define LOAD_AVG_MAX_N 206

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_16
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf5257d14,0xeac0c6e6,0xe0ccdeeb,
        0xd744fcc9,0xce248c14,0xc5672a10,0xbd08a39e,
        0xb504f333,0xad583ee9,0xa5fed6a9,0x9ef5325f,
        0x9837f050,0x91c3d373,0x8b95c1e3,0x85aac367,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1568, 3070, 4508, 5885, 7204, 8467, 9676,10834,11943,13005,
        14022,14996,15928,16821,17676,18495,
};

#define LOAD_AVG_PERIOD 16
#define LOAD_AVG_MAX 38612
#define LOAD_AVG_MAX_N 183

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_14
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf3a24b24,0xe7dd818c,0xdcaa4034,
        0xd2017f74,0xc7dc8e94,0xbe350f94,0xb504f333,
        0xac46751e,0xa3f41854,0x9c08a3b0,0x947f1ea5,
        0x8d52ce1f,0x867f318b,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1558, 3041, 4452, 5795, 7073, 8290, 9448,10550,11599,12597,
        13547,14451,15311,16130,
};

#define LOAD_AVG_PERIOD 14
#define LOAD_AVG_MAX 33889
#define LOAD_AVG_MAX_N 159

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_12
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xf1a1bf37,0xe411f039,0xd744fcc9,
        0xcb2ff529,0xbfc886ba,0xb504f333,0xaadc0846,
        0xa14517cb,0x9837f050,0x8facd61d,0x879c7c96,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1546, 3005, 4382, 5682, 6909, 8067, 9160,10191,11165,12084,
        12951,13770,
};

#define LOAD_AVG_PERIOD 12
#define LOAD_AVG_MAX 29167
#define LOAD_AVG_MAX_N 136

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_10
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xeedb4007,0xdedc66d6,0xcfefc5e5,
        0xc203001c,0xb504f333,0xa8e5a29d,0x9d9623df,
        0x93088c35,0x892fdf70,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1528, 2953, 4283, 5524, 6682, 7762, 8770, 9711,10588,11407,
};

#define LOAD_AVG_PERIOD 10
#define LOAD_AVG_MAX 24445
#define LOAD_AVG_MAX_N 113

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_8
static const u32 runnable_avg_yN_inv[] = {
        0xffffffff,0xeac0c6e6,0xd744fcc9,0xc5672a10,
        0xb504f333,0xa5fed6a9,0x9837f050,0x8b95c1e3,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1502, 2879, 4142, 5300, 6362, 7336, 8229, 9048,
};

#define LOAD_AVG_PERIOD 8
#define LOAD_AVG_MAX 19724
#define LOAD_AVG_MAX_N 91

#endif
